### ISSUE TITLE
"make build" on master fails with fatal error: mlock failed on ubuntu 20.04

### ISSUE THREAD

**Issue by SandeepPissay** [minio/minio-operator#102]
I'm facing the below build issue on master. 

```
root@ubuntu:~/minio-operator# make build
Sending build context to Docker daemon  3.793MB
Step 1/17 : FROM golang:1.14.0
 ---> 25c4671a1478
Step 2/17 : ADD go.mod /go/src/github.com/minio/minio-operator/go.mod
 ---> Using cache
 ---> 17423457e5d4
Step 3/17 : ADD go.sum /go/src/github.com/minio/minio-operator/go.sum
 ---> Using cache
 ---> 38b010cb9754
Step 4/17 : WORKDIR /go/src/github.com/minio/minio-operator/
 ---> Using cache
 ---> 61a1ce2cd69f
Step 5/17 : RUN apt-get update -y && apt-get install -y ca-certificates
 ---> Using cache
 ---> 406d5e7b0aa3
Step 6/17 : RUN go mod download
 ---> Using cache
 ---> d064a6aec85b
Step 7/17 : ADD . /go/src/github.com/minio/minio-operator/
 ---> Using cache
 ---> 9df94c863b75
Step 8/17 : WORKDIR /go/src/github.com/minio/minio-operator/
 ---> Using cache
 ---> 802ac297e3c1
Step 9/17 : ENV CGO_ENABLED=0
 ---> Using cache
 ---> 9c93a8558e05
Step 10/17 : ARG ldflags
 ---> Using cache
 ---> 69e93914d809
Step 11/17 : ENV env_ldflags=$ldflags
 ---> Using cache
 ---> 579e07d448c1
Step 12/17 : RUN go build -ldflags "$env_ldflags" -a -o minio-operator .
 ---> Running in 82f3ab6ae916
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed

runtime stack:
runtime.throw(0xa3b43e, 0xc)
        /usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc000082600)
        /usr/local/go/src/runtime/os_linux_x86.go:72 +0x107
runtime.mpreinit(0xc000080700)
        /usr/local/go/src/runtime/os_linux.go:341 +0x78
runtime.mcommoninit(0xc000080700)
        /usr/local/go/src/runtime/proc.go:630 +0x108
runtime.allocm(0xc000037800, 0xa82448, 0xc0004da700)
        /usr/local/go/src/runtime/proc.go:1390 +0x14e
runtime.newm(0xa82448, 0xc000037800)
        /usr/local/go/src/runtime/proc.go:1704 +0x39
runtime.startm(0xc000037800, 0xec8801)
        /usr/local/go/src/runtime/proc.go:1869 +0x12a
runtime.handoffp(0xc000037800)
        /usr/local/go/src/runtime/proc.go:1907 +0x2d3
runtime.retake(0x1c3aa6e332fe, 0x0)
        /usr/local/go/src/runtime/proc.go:4628 +0x157
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4537 +0x138
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1097 +0xc3
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1062 +0x6e

goroutine 1 [runnable]:
syscall.Syscall(0x0, 0x8, 0xc00068c000, 0x1000, 0x1000, 0x1000, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0xc00068c000, 0x1000, 0x1000, 0x0, 0x400, 0x400)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
syscall.Read(...)
        /usr/local/go/src/syscall/syscall_unix.go:189
internal/poll.(*FD).Read(0xc0007a0000, 0xc00068c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:165 +0x133
os.(*File).read(...)
        /usr/local/go/src/os/file_unix.go:263
os.(*File).Read(0xc000294068, 0xc00068c000, 0x1000, 0x1000, 0x40d674, 0x7fe15474d3a0, 0x0)
        /usr/local/go/src/os/file.go:116 +0x71
bufio.(*Reader).fill(0xc0007a0060)
        /usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc0007a0060, 0x7fe15474d3a0, 0x97a401, 0x101000000000000)
        /usr/local/go/src/bufio/bufio.go:252 +0x39
cmd/go/internal/imports.(*importReader).readByte(0xc0001bea80, 0xc0001bea48)
        /usr/local/go/src/cmd/go/internal/imports/read.go:44 +0x32
cmd/go/internal/imports.(*importReader).peekByte(0xc0001bea80, 0x97a601, 0x99a701)
        /usr/local/go/src/cmd/go/internal/imports/read.go:77 +0x1c2
cmd/go/internal/imports.(*importReader).readKeyword(0xc0001bea80, 0xa3807e, 0x7)
        /usr/local/go/src/cmd/go/internal/imports/read.go:125 +0x34
cmd/go/internal/imports.ReadImports(0xb2d5e0, 0xc000294068, 0x0, 0xc0001bebf0, 0xc000294068, 0x0, 0x0, 0x7fe15470b008, 0x10)
        /usr/local/go/src/cmd/go/internal/imports/read.go:218 +0xc8
cmd/go/internal/imports.scanFiles(0xc000450c00, 0x3c, 0x40, 0xc0001a80c0, 0x0, 0xc000450c00, 0x20, 0x40, 0xc0001bee38, 0x40e388, ...)
        /usr/local/go/src/cmd/go/internal/imports/scan.go:57 +0x26b
cmd/go/internal/imports.ScanDir(0xc000786e20, 0x19, 0xc0001a80c0, 0x97a200, 0x4f2587, 0xc000024e71, 0x7, 0x8dd540, 0xffffffffffffffff, 0x97a480, ...)
        /usr/local/go/src/cmd/go/internal/imports/scan.go:39 +0x20e
cmd/go/internal/modload.scanDir(0xc000786e20, 0x19, 0xc0001a80c0, 0x0, 0x0, 0x0, 0xc000786e20, 0x19, 0x0, 0x0, ...)
        /usr/local/go/src/cmd/go/internal/modload/load.go:868 +0x5a
cmd/go/internal/modload.(*loader).doPkg(0xc000072540, 0x9a58e0, 0xc0005ff860)
        /usr/local/go/src/cmd/go/internal/modload/load.go:776 +0x46c
cmd/go/internal/par.(*Work).runner(0xc000020380)
        /usr/local/go/src/cmd/go/internal/par/work.go:101 +0x157
cmd/go/internal/par.(*Work).Do(0xc000020380, 0xa, 0xc00005f9f0)
        /usr/local/go/src/cmd/go/internal/par/work.go:69 +0xbf
cmd/go/internal/modload.(*loader).load(0xc000072540, 0xc0001bf728)
        /usr/local/go/src/cmd/go/internal/modload/load.go:645 +0xb17
cmd/go/internal/modload.ImportPathsQuiet(0xc0000200f0, 0x1, 0x1, 0xc0001a80c0, 0xc0001a3d40, 0xc00005b7d0, 0x41634f)
        /usr/local/go/src/cmd/go/internal/modload/load.go:204 +0x2df
cmd/go/internal/modload.ImportPaths(0xc0000200f0, 0x1, 0x1, 0x416fb6, 0x7fe15613b300, 0x100)
        /usr/local/go/src/cmd/go/internal/modload/load.go:58 +0x5d
cmd/go/internal/load.ImportPaths(0xc0000200f0, 0x1, 0x1, 0x400, 0x203000, 0x400)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:2114 +0x5f
cmd/go/internal/load.PackagesAndErrors(0xc0000200f0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:2061 +0xf1
cmd/go/internal/load.PackagesForBuild(0xc0000200f0, 0x1, 0x1, 0xa35d60, 0x2, 0x1)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:2123 +0x5d
cmd/go/internal/work.runBuild(0xebde20, 0xc0000200f0, 0x1, 0x1)
        /usr/local/go/src/cmd/go/internal/work/build.go:348 +0x88
main.main()
        /usr/local/go/src/cmd/go/main.go:189 +0x569

```

I see that the kernel version and ulimit -l meets the criteria described in the above error:
```
root@ubuntu:~/minio-operator# uname -r
5.4.0-29-generic

root@ubuntu:~/minio-operator# ulimit -l
unlimited

```

**Comment by harshavardhana** [comment]
This means your docker has mlock disabled in your container environment, builds fine locally on ubuntu 20.04

```
~ make
Sending build context to Docker daemon  24.89MB
Step 1/17 : FROM golang:1.14
1.14: Pulling from library/golang
90fe46dd8199: Pull complete 
35a4f1977689: Pull complete 
bbc37f14aded: Pull complete 
74e27dc593d4: Pull complete 
38b1453721cb: Pull complete 
780391780e20: Pull complete 
0f7fd9f8d114: Pull complete 
Digest: sha256:e36e74d9770fa9fbf06cda4494ae1e6442637e53d71fbd77560ac3eb976a1417
Status: Downloaded newer image for golang:1.14
 ---> 2421885b04da
Step 2/17 : ADD go.mod /go/src/github.com/minio/minio-operator/go.mod
 ---> a16013a9be1c
Step 3/17 : ADD go.sum /go/src/github.com/minio/minio-operator/go.sum
 ---> c40577630cc5
Step 4/17 : WORKDIR /go/src/github.com/minio/minio-operator/
 ---> Running in 63de9d6b32e7
Removing intermediate container 63de9d6b32e7
 ---> ac5f100314ed
Step 5/17 : RUN apt-get update -y && apt-get install -y ca-certificates
 ---> Running in 04f7c35342ae
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [198 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7905 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Fetched 8347 kB in 3s (3281 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20190110).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Removing intermediate container 04f7c35342ae
 ---> 061d784e4c68
Step 6/17 : RUN go mod download
 ---> Running in 8da4af2ab980
Removing intermediate container 8da4af2ab980
 ---> dc03f3a9e942
Step 7/17 : ADD . /go/src/github.com/minio/minio-operator/
 ---> f1bc84563ff7
Step 8/17 : WORKDIR /go/src/github.com/minio/minio-operator/
 ---> Running in 741adcd0bde1
Removing intermediate container 741adcd0bde1
 ---> 9bc712392a03
Step 9/17 : ENV CGO_ENABLED=0
 ---> Running in 7faf838d58f9
Removing intermediate container 7faf838d58f9
 ---> d988713c2214
Step 10/17 : ARG ldflags
 ---> Running in 3ecf00a5237a
Removing intermediate container 3ecf00a5237a
 ---> 7e79899b82ee
Step 11/17 : ENV env_ldflags=$ldflags
 ---> Running in 0831f6352a47
Removing intermediate container 0831f6352a47
 ---> d1d5902c817a
Step 12/17 : RUN go build -ldflags "$env_ldflags" -a -o minio-operator .
 ---> Running in 40cb3946f8bf
Removing intermediate container 40cb3946f8bf
 ---> 0952ab7f35dd
Step 13/17 : FROM scratch
 ---> 
Step 14/17 : LABEL maintainer="MinIO Inc <dev@min.io>"
 ---> Running in 66a59eb9296f
Removing intermediate container 66a59eb9296f
 ---> 192c2b01d47a
Step 15/17 : COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 ---> 1bd317213aeb
Step 16/17 : COPY --from=0 /go/src/github.com/minio/minio-operator/minio-operator .
 ---> 162f905297d8
Step 17/17 : CMD ["/minio-operator"]
 ---> Running in 44b15fe3f34f
Removing intermediate container 44b15fe3f34f
 ---> 7a8f6b91473b
Successfully built 7a8f6b91473b
Successfully tagged minio/k8s-operator:2.0.0-1-g6df24bd
```

``` 
~ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
```
