### ISSUE TITLE
Crash in minioIOinstance validator

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-operator#171]
## Expected Behavior
No crashes

## Current Behavior
```
goroutine 47 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x13e1a80, 0x21990c0)
        runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x13e1a80, 0x21990c0)
        runtime/panic.go:679 +0x1b2
github.com/minio/minio-operator/pkg/apis/operator.min.io/v1.(*MinIOInstance).Validate(0xc000196a00, 0xc000196a00, 0x5)
        github.com/minio/minio-operator@/pkg/apis/operator.min.io/v1/helper.go:421 +0x3e
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).syncHandler(0xc000474000, 0xc0006f8a30, 0xd, 0xc00042bcb0, 0xc0004c0ca0)
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:346 +0x2e0
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1(0xc000474000, 0x13785c0, 0xc000162cc0, 0x0, 0x0)
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:294 +0x16c
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc000474000, 0x203000)
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:302 +0x53
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).runWorker(0xc000474000)
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:255 +0x62
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00088c030)
        k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00088c030, 0x1789340, 0xc0008060f0, 0xc0001cc501, 0xc000160ba0)
        k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00088c030, 0x3b9aca00, 0x0, 0x1, 0xc000160ba0)
        k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc00088c030, 0x3b9aca00, 0xc000160ba0)
        k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).Start
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:238 +0x1f2
```

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Remove volumeClaimTemplates from the minioinstance.yaml and observe the crash

## Context
Stability issue

## Regression
Not sure

## Your Environment
k8s 1.18.3, latest minio-operator

**Comment by dvaldivia** [comment]
Can you share the YAML for the `MinIOInstnace` ?

**Comment by harshavardhana** [comment]
> Can you share the YAML for the `MinIOInstnace` ?

Just remove this

```diff
git diff
diff --git a/examples/minioinstance.yaml b/examples/minioinstance.yaml
index 136cf00..15a6448 100644
--- a/examples/minioinstance.yaml
+++ b/examples/minioinstance.yaml
@@ -57,18 +57,6 @@ spec:
   mountPath: /export
   ## Sub path inside Mount path where MinIO starts. Defaults to "".
   # subPath: /data
-  ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO cluster.
-  ## Please do not change the volumeClaimTemplate field while expanding the cluster, this may
-  ## lead to unbound PVCs and missing data
-  volumeClaimTemplate:
-    metadata:
-      name: data
-    spec:
-      accessModes:
-        - ReadWriteOnce
-      resources:
-        requests:
-          storage: 1Ti
   ## Secret with credentials to be used by MinIO instance.
   credsSecret:
     name: minio-creds-secret
```

**Comment by dvaldivia** [comment]
Can you also share the operator version used? on master this error seems to originate from 
```
if err = madmClnt.AddCannedPolicy(context.Background(), MCSAdminPolicyName, &p); err != nil {
		return err
	}
```
however this cannot produce an NPE unless `madmClnt` is null, the previous stack call is also different from master

**Comment by harshavardhana** [comment]
```
    spec:
      serviceAccountName: minio-operator
      containers:
        - name: minio-operator
          image: minio/k8s-operator:2.0.6
          imagePullPolicy: IfNotPresent
```

**Comment by harshavardhana** [comment]
whatever is referenced in the master I just used

**Comment by dvaldivia** [comment]
I see, we still have `2.0.6` on the [master install yaml](https://github.com/minio/minio-operator/blob/master/minio-operator.yaml)

**Comment by dvaldivia** [comment]
can you try on `2.0.9` and tell me if you see the crash?

**Comment by harshavardhana** [comment]
Still crashing

```
goroutine 338 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x13e1b60, 0x219a0c0)
        runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x13e1b60, 0x219a0c0)
        runtime/panic.go:679 +0x1b2
github.com/minio/minio-operator/pkg/apis/operator.min.io/v1.(*MinIOInstance).Validate(0xc000188a00, 0xc000188a00, 0x5)
        github.com/minio/minio-operator@/pkg/apis/operator.min.io/v1/helper.go:418 +0x3e
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).syncHandler(0xc000474000, 0xc0004f3a90, 0xd, 0xc0003ff460, 0xc000000008)
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:364 +0x2e0
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1(0xc000474000, 0x13785e0, 0xc00067be50, 0x0, 0x0)
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:312 +0x16c
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc000474000, 0x21b8640)
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:320 +0x53
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).runWorker(0xc000474000)
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:273 +0x62
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0008902d0)
        k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008902d0, 0x1789580, 0xc000806330, 0xc00064e501, 0xc000162ba0)
        k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008902d0, 0x3b9aca00, 0x0, 0xc00064a001, 0xc000162ba0)
        k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc0008902d0, 0x3b9aca00, 0xc000162ba0)
        k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).Start
        github.com/minio/minio-operator@/pkg/controller/cluster/main-controller.go:256 +0x1f2
```

**Comment by dvaldivia** [comment]
Found it, the missing volume spec causes the NPE

```
	// Make sure the storage request is not 0
	if mi.Spec.VolumeClaimTemplate.Spec.Resources.Requests.Storage().Value() <= 0 {
		return errors.New("volume size must be greater than 0")
	}
```
Therefore we need to declare "Invalid Volume Claim Template" if the `MinIOTenant` doesn't declare this
