### ISSUE TITLE
Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)

### ISSUE THREAD

**Issue by cameronbraid** [minio/minio-operator#83]
operator: docker.io/minio/k8s-operator:1.0.8
kubernetes : Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

```
E0421 05:53:16.217716       1 runtime.go:66] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/runtime/runtime.go:72
/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/runtime/runtime.go:65
/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/runtime/runtime.go:51
/home/harsha/.gimme/versions/go1.13.10.linux.amd64/src/runtime/panic.go:679
/home/harsha/.gimme/versions/go1.13.10.linux.amd64/src/runtime/panic.go:75
/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/resources/statefulsets/statefulset.go:144
/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/resources/statefulsets/statefulset.go:251
/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:333
/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:248
/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:256
/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:209
/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:133
/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:134
/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:88
/home/harsha/.gimme/versions/go1.13.10.linux.amd64/src/runtime/asm_amd64.s:1357
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 115 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1146dc0, 0xc0002860c0)
	/home/harsha/.gimme/versions/go1.13.10.linux.amd64/src/runtime/panic.go:679 +0x1b2
github.com/minio/minio-operator/pkg/resources/statefulsets.minioServerContainer(0xc0000f0480, 0xc0003eb500, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/resources/statefulsets/statefulset.go:144 +0x678
github.com/minio/minio-operator/pkg/resources/statefulsets.NewForCluster(0xc0000f0480, 0xc0003eb500, 0x17, 0x8)
	/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/resources/statefulsets/statefulset.go:251 +0x37c
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).syncHandler(0xc000300000, 0xc0001d86c0, 0x16, 0xc00056a2d0, 0xc0000aed28)
	/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:333 +0xcd2
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1(0xc000300000, 0x1032a60, 0xc0001e4c30, 0x0, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:248 +0x169
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc000300000, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:256 +0x50
github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).runWorker(0xc000300000)
	/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:209 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00021a040)
	/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:133 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00021a040, 0x3b9aca00, 0x0, 0x1, 0xc0000a69c0)
	/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00021a040, 0x3b9aca00, 0xc0000a69c0)
	/home/harsha/mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:88 +0x4d
created by github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).Run
	/home/harsha/mygo/src/github.com/minio/minio-operator/pkg/controller/cluster/controller.go:195 +0x29a

```

**Comment by harshavardhana** [comment]
thanks for the report @cameronbraid

**Comment by cameronbraid** [comment]
Looks to be a backwards compat issue.. as I had a minio instance of a slightly older format

once I added
```
  selector:
    matchLabels:
      app: minio-standalone # Should match spec.metadata.labels
  zones:
   ....
```
it started fine

**Comment by harshavardhana** [comment]
we made a new release PTAL its a breaking change, the crash should be fixed as well.
